version: '3.3'

services:
  otar_importer:
    build: .
    container_name: otar_biocypher
    command: ["neo4j"]
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7475:7474
      - 7688:7687
 #   restart: always

#volumes:
#  otar_setup_volume:
#  otar_data_volume:
