[tool.poetry]
name = "otar-biocypher"
version = "0.1.0"
description = "BioCypher Open Targets Knowledge Graph adapter"
authors = ["Sebastian Lobentanzer <sebastian.lobentanzer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
biocypher = {path = "../BioCypher", develop = true}
snakeviz = "^2.1.1"
pyspark = "^3.3.1"

[tool.poetry.dev-dependencies]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
