Title: BioCypher graph schema configuration file

# This configuration file establishes the hierarchy and connectivity in a newly
# set-up BioCypher property graph database. Naming should adhere to Biolink
# nomenclature (available at https://biolink.github.io/biolink-model/ or via 
# the python module 'biolink-model-toolkit').

# The BioCypher YAML file specifies only the leaves of the hierarchy tree of
# the desired graph; the hierarchical structure of entities will be derived 
# from the Biolink model. Thus, only the immediate constituents of the graph
# need to be specified in the schema config.


# ---
# "Named Things"
# ---

article:
  represented_as: node
  preferred_id: pubmed
  label_in_input: GraphPublication

biological entity:
  represented_as: node
  preferred_id: [reactome, signor]
  label_in_input: [reactome_unknown_participant, signor_unknown_participant]

DNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact.molecule, genbank, ensembl, reactome, refseq]
  label_in_input: [intact_dna, genbank_dna, ensembl_dna, reactome_dna, refseq_dna]

dsDNA sequence:
  is_a: [DNA sequence, nucleic acid entity]
  represented_as: node
  preferred_id: [intact.molecule, uniparc, genbank, ensembl, pubmed, refseq]
  label_in_input: [
    intact_dsdna, 
    uniprot_archive_dsdna, 
    genbank_dsdna, 
    ensembl_dsdna, 
    pubmed_dsdna,
    refseq_dsdna
  ]

evidence type:
  represented_as: node
  preferred_id: id
  label_in_input: GraphEvidenceType

experiment:
  is_a: information content entity
  represented_as: node
  preferred_id: id
  label_in_input: GraphExperiment

ssDNA sequence:
  is_a: [DNA sequence, nucleic acid entity]
  represented_as: node
  preferred_id: [intact.molecule, genbank, ensembl, chebi]
  label_in_input: [intact_ssdna, genbank_ssdna, ensembl_ssdna, chebi_ssdna]

gene:
  represented_as: node
  preferred_id: exac.gene
  label_in_input: gene

gene grouping mixin:
  represented_as: node
  preferred_id: [intact.molecule, uniprot, signor]
  label_in_input: [intact_molecule_set, uniprot_molecule_set, signor_molecule_set]

microRNA:
  represented_as: node
  preferred_id: [rnacentral, ensembl, mirbase]
  label_in_input: [rnacentral_mirna, ensembl_mirna, mirbase_mirna]

peptide:
  is_a: polypeptide
  represented_as: node
  preferred_id: [intact.molecule, dip]
  label_in_input: [intact_peptide, dip_peptide]

peptide precursor:
  is_a: [peptide, polypeptide]
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_peptide_precursor

phenotypic feature:
  represented_as: node
  preferred_id: signor
  label_in_input: signor_phenotype

poly a sequence motif:
  is_a: nucleic acid sequence motif
  represented_as: node
  preferred_id: chebi
  label_in_input: chebi_poly_a

protein:
  represented_as: node
  preferred_id: [
    uniprot, 
    intact.molecule, 
    uniparc, 
    ncbigene, 
    genbank, 
    dip, 
    ipi, 
    refseq, 
    drugbank, 
    chembl, 
    ensembl
  ]
  label_in_input: [
    uniprot_protein, 
    intact_protein, 
    uniprot_archive_protein, 
    entrez_protein,
    genbank_protein,
    dip_protein,
    ipi_protein,
    refseq_protein,
    drugbank_protein,
    chembl_protein,
    ensembl_protein
  ]

protein isoform:
  is_a: protein
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_protein_isoform

protein complex:
  is_a: macromolecular complex mixin
  represented_as: node
  preferred_id: [signor, complexportal]
  label_in_input: [signor_complex, complexportal_complex]

protein precursor:
  is_a: protein
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_protein_precursor

# OTAR "rna" may be too generic; where are the actual Transcripts in the 
# sense of the central dogma? Are they exclusively in "mrna" (below)?
RNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [
    intact.molecule, 
    rnacentral, 
    reactome, 
    genbank, 
    ncbigene, 
    ensembl, 
    refseq
  ]
  label_in_input: [
    intact_rna, 
    rnacentral_rna, 
    reactome_rna, 
    genbank_rna,
    entrez_rna,
    ensembl_rna,
    refseq_rna
  ]

guide RNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact.molecule, rnacentral]
  label_in_input: [intact_grna, rnacentral_grna]

lncRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact.molecule, refseq, rnacentral, ensembl]
  label_in_input: [intact_lncrna, refseq_lncrna, rnacentral_lncrna, ensembl_lncrna]

# neither scientific name nor taxon id are unique
# includes cell lines, samples, tissues, etc.
organismal entity:
  represented_as: node
  preferred_id: ncbitaxon
  label_in_input: GraphOrganism

rRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact.molecule, genbank, rnacentral, ensembl, ncbigene]
  label_in_input: [intact_rrna, genbank_rrna, rnacentral_rrna, ensembl_rrna, entrez_rrna]

snoRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [rnacentral]
  label_in_input: [snorna]

tRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [genbank, ensembl, chebi, rnacentral]
  label_in_input: [genbank_trna, ensembl_trna, chebi_trna, rnacentral_trna]

small molecule:
  represented_as: node
  preferred_id: [chebi, chembl, intact.molecule, pubchem.compound]
  label_in_input: [chebi_small_molecule, chembl_small_molecule, intact_small_molecule, pubchem_compound]

stable complex:
  is_a: macromolecular complex mixin
  represented_as: node
  preferred_id: complexportal
  label_in_input: complexportal_stable_complex

stimulus:
  is_a: biological entity
  represented_as: node
  preferred_id: signor
  label_in_input: signor_stimulus

transcript:
  represented_as: node
  preferred_id: [ensembl, intact.molecule, hgnc, genbank, refseq]
  label_in_input: [ensembl_mrna, intact_mrna, hgnc_mrna, genbank_mrna, refseq_mrna]

xenobiotic:
  is_a: small molecule
  represented_as: node
  preferred_id: [pubchem.compound, chebi]
  label_in_input: [pubchem_xenobiotic, chebi_xenobiotic]

# ---
# Associations
# ---

# OBO MI stratification from interaction type: https://www.ebi.ac.uk/ols/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_0190&lang=en&viewMode=All&siblings=false

colocalisation:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  # merge for now for simplicity
  label_in_input: [colocalization, proximity]

functional association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  label_in_input: functional association

molecular association psimi:
  is_a: association
  # weakest form of inference, co-detection of entities. naming clash
  # with biolink association; the "molecular" could be a way around
  # although it is the parent of association in the PSI-MI schema
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  # direct inheritance chain without branches
  label_in_input: association

physical association:
  # stronger inference; simply put found in the same complex; does not
  # imply direct contact
  is_a: [molecular association psimi, association]
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  # direct inheritance chain without branches
  label_in_input: physical association

direct interaction:
  is_a: [
    physical association, 
    molecular association psimi, 
    association,
  ]
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  # direct inheritance chain without branches
  label_in_input: direct interaction

enzymatic interaction:
  # aggregate class of specific direct interactions
  # create virtual leaves for all labels?
  is_a: [
    direct interaction,
    physical association psimi,
    association
  ]
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  label_in_input: [
    acetylation,
    deacetylation,
    phosphorylation,
    protein cleavage,
    cleavage,
    gtpase reaction,
    lipid cleavage-2,
    lipid cleavage,
    enzymatic reaction,
    adp ribosylation,
    ubiquitination,
    redox reaction,
    hydroxylation,
    methylation,
    deamidation,
    sumoylation,
    neddylation,
    dephosphorylation,
    dna cleavage,
    glycosylation,
    demethylation,
    atpase reaction,
    deubiquitination,
    covalent binding,
    phosphotransfer,
    ampylation,
    deamination,
    disulfide bond,
    aminoacylation,
    rna cleavage,
    palmitoylation,
    lipid addition,
    de-adp-ribosylation reaction,
    rna elongation,
    guanine nucleotide exchange factor reaction,
    transglutamination,
    deneddylation,
    proline isomerization  reaction,
    decarboxylation,
    sulfurtransfer,
    triphosphatase react,
    carboxylation,
    isomerase reaction,
    phospholipase reaction,
    p_patetheinylation,
    gtpase-activating protein reaction,
    desumoylation,
    s-nitrosylation,
    tyrosination,
  ]

# covalent binding is only 6 small molecule - protein interactions.
covalent binding:
  # aggregate class of specific direct interactions
  is_a: [
    direct interaction,
    physical association psimi,
    association
  ]
  represented_as: node
  preferred_id: intact
  source: small molecule
  target: protein
  label_in_input: covalent binding

#################### NON PSI-MI INTERACTIONS ####################
experiment to article association:
  is_a: association
  represented_as: edge
  preferred_id: id
  source: experiment
  target: article
  label_in_input: EXPERIMENT_TO_PUBLICATION

experiment to organism association:
  is_a: association
  represented_as: edge
  preferred_id: id
  source: experiment
  target: organism
  label_in_input: EXPERIMENT_TO_ORGANISM

experiment to evidence type association:
  is_a: association
  represented_as: edge
  preferred_id: id
  source: experiment
  target: evidence type
  label_in_input: EXPERIMENT_TO_DETECTION_METHOD

interaction to experiment association:
  is_a: association
  represented_as: edge
  preferred_id: id
  source: interaction # does not exist, granular subtypes above
  target: experiment
  label_in_input: INTERACTION_TO_EXPERIMENT

interactor to organism association:
  is_a: association
  represented_as: edge
  preferred_id: id
  source: interactor
  target: organism
  label_in_input: INTERACTOR_TO_ORGANISM

experiment to interactor association:
  is_a: association
  represented_as: edge
  preferred_id: id
  source: experiment
  target: interactor
  label_in_input: PARTICIPANT_DETECTION_METHOD

# self interactions are not in the graph.

# ### From OTAR, Barrio-Hernandez query:
# ## currently UNUSED
# # 'MI:0320', ribonucleic acid
# # quite generic; probes, k-mers (shared probably), telomerase RNA
# # protein_rna: intact, wwpdb, emdb, reactome
# # rna_protein: intact, wwpdb, emdb, rcsb pdb
# # only reactome does not have interaction ID
# intact.protein to RNA sequence association:
#   is_a: [protein to RNA sequence association, association]
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: RNASequence
#   label_in_input: [
#     protein_rna,
#     protein_rna,
#     protein_rna,
#     rna_protein,
#     rna_protein,
#     rna_protein,
#     rna_protein,
#   ]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # hack: represent virtual leaves explicitly
# reactome.protein to RNA sequence association:
#   is_a: [protein to RNA sequence association, association]
#   represented_as: node
#   preferred_id: id
#   source: protein
#   target: RNASequence
#   label_in_input: protein_rna_reactome
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str


# # 'MI:0321', catalytic rna
# # no "catalytic rna" in OTAR graph

# # 'MI:0322', guide rna
# # only intact and wwpdb
# protein to guide RNA association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: GuideRNASequence
#   label_in_input: [protein_grna_intact, protein_grna_wwpdb]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # 'MI:0323', heterogeneous nuclear rna
# # not in OTAR graph

# # 'MI_0325', transfer rna
# # few; intact, emdb, wwpdb
# protein to tRNA association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: tRNASequence
#   label_in_input: [
#     protein_trna_intact,
#     trna_protein_intact,
#     protein_trna_emdb,
#     protein_trna_wwpdb
#   ]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # 'MI:0324', messenger rna
# # only intact
# protein to mRNA association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: mRNASequence
#   label_in_input: [
#     protein_mrna_intact,
#     mrna_protein_intact
#   ]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # 'MI:0608', ribosomal rna
# # few; intact, emdb, wwpdb, rcsb pdb
# protein to rRNA association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: rRNASequence
#   label_in_input: [
#     rrna_protein_intact,
#     rrna_protein_wwpdb,
#     rrna_protein_rcsb pdb,
#     protein_rrna_intact,
#     rrna_protein_emdb,
#     protein_rrna_emdb,
#     protein_rrna_wwpdb
#   ]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # 'MI:0609', small nucleolar rna
# # few, only intact
# protein to snoRNA association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: snoRNASequence
#   label_in_input: protein_snorna_intact
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # 'MI:0610', small interfering rna
# # not in OTAR graph

# # 'MI:0611', signal recognition particle rna
# # not in OTAR graph

# # 'MI:0679', poly adenine
# # few, only intact
# protein to poly a sequence motif association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: PolyASequenceMotif
#   label_in_input: [
#     poly a_protein_intact,
#     protein_poly a_intact
#   ]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # 'MI:2190', long non-coding ribonucleic acid
# # few, only intact
# protein to lncRNA sequence association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: lncRNASequence
#   label_in_input: [
#     protein_lncrna_intact,
#     lncrna_protein_intact
#   ]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str

# # 'MI:2204', micro rna few and only intact, BUT there are quite some
# # more mRNA-miRNA interactions, which are disregarded in this schema;
# # may be a point of improvement to include those protein-mrna-mirna
# # relations
# protein to microRNA sequence association:
#   is_a: association
#   represented_as: node
#   preferred_id: intact
#   source: protein
#   target: microRNA
#   label_in_input: [
#     mirna_protein_intact,
#     protein_mirna_intact
#   ]
#   properties:
#     ac: str
#     shortName: str
#     isNegative: str
#     isInferred: str
#     interactionTypeShortName: str
#     interactionTypeFullName: str
#     interactionTypeIdentifierStr: str
