Title: BioCypher graph schema configuration file

# This configuration file establishes the hierarchy and connectivity in a newly
# set-up BioCypher property graph database. Naming should adhere to Biolink
# nomenclature (available at https://biolink.github.io/biolink-model/ or via 
# the python module 'biolink-model-toolkit').

# The BioCypher YAML file specifies only the leaves of the hierarchy tree of
# the desired graph; the hierarchical structure of entities will be derived 
# from the Biolink model. Thus, only the immediate constituents of the graph
# need to be specified in the schema config.


# ---
# "Named Things"
# ---
# The implementation of named things is fairly straightforward, since they are
# usually represented in node form, which is also the Biolink recommendation.
# The same is not true for associations.
#
# A little more complex is the representation of aggregates of named things, 
# for instance in the case of functional protein complexes. These are represented
# by so-called "mixins", which are not officially part of the hierarchy.

Article:
  represented_as: node
  preferred_id: pubmed
  label_in_input: GraphPublication
  properties:
    ac: str
    title: str
    journal: str
    authors: str
    publicationDate: str

BiologicalEntity:
  represented_as: node
  preferred_id: [reactome, signor]
  label_in_input: [reactome_unknown_participant, signor_unknown_participant]
  properties:
    preferredName: str
    shortName: str

ChemicalEntity:
  represented_as: node
  preferred_id: pubchem.substance
  label_in_input: pubchem_substance
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

DNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [intact.molecule, genbank, ensembl, reactome, refseq]
  label_in_input: [intact_dna, genbank_dna, ensembl_dna, reactome_dna, refseq_dna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

dsDNASequence:
  is_a: [DNASequence, NucleicAcidEntity]
  represented_as: node
  preferred_id: [intact.molecule, uniparc, genbank, ensembl, pubmed, refseq]
  label_in_input: [
    intact_dsdna, 
    uniprot_archive_dsdna, 
    genbank_dsdna, 
    ensembl_dsdna, 
    pubmed_dsdna,
    refseq_dsdna
  ]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

ssDNASequence:
  is_a: [DNASequence, NucleicAcidEntity]
  represented_as: node
  preferred_id: [intact.molecule, genbank, ensembl, chebi]
  label_in_input: [intact_ssdna, genbank_ssdna, ensembl_ssdna, chebi_ssdna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

Gene:
  represented_as: node
  preferred_id: exac.gene
  label_in_input: gene
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

GeneGroupingMixin:
  represented_as: node
  preferred_id: [intact.molecule, uniprot, signor]
  label_in_input: [intact_molecule_set, uniprot_molecule_set, signor_molecule_set]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

microRNA:
  represented_as: node
  preferred_id: [rnacentral, ensembl, mirbase]
  label_in_input: [rnacentral_mirna, ensembl_mirna, mirbase_mirna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    
NucleicAcidEntity:
  represented_as: node
  preferred_id: [intact.molecule, reactome, genbank, ensembl]
  label_in_input: [
    intact_nucleic_acid, 
    reactome_nucleic_acid, 
    genbank_nucleic_acid, 
    ensembl_nucleic_acid
  ]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

Peptide:
  is_a: Polypeptide
  represented_as: node
  preferred_id: [intact.molecule, dip]
  label_in_input: [intact_peptide, dip_peptide]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

PeptidePrecursor:
  is_a: [Peptide, Polypeptide]
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_peptide_precursor
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

PhenotypicFeature:
  represented_as: node
  preferred_id: signor
  label_in_input: signor_phenotype
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

PolyASequenceMotif:
  is_a: NucleicAcidSequenceMotif
  represented_as: node
  preferred_id: chebi
  label_in_input: chebi_poly_a
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

Protein:
  represented_as: node
  preferred_id: [
    uniprot, 
    intact.molecule, 
    uniparc, 
    ncbigene, 
    genbank, 
    dip, 
    ipi, 
    refseq, 
    drugbank, 
    chembl, 
    ensembl
  ]
  label_in_input: [
    uniprot_protein, 
    intact_protein, 
    uniprot_archive_protein, 
    entrez_protein,
    genbank_protein,
    dip_protein,
    ipi_protein,
    refseq_protein,
    drugbank_protein,
    chembl_protein,
    ensembl_protein
  ]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

ProteinIsoform:
  is_a: Protein
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_protein_isoform
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

ProteinPrecursor:
  is_a: Protein
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_protein_precursor
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

ProteinComplex:
  is_a: MacromolecularComplexMixin
  represented_as: node
  preferred_id: [signor, complexportal]
  label_in_input: [signor_complex, complexportal_complex]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

# OTAR "rna" may be too generic; where are the actual Transcripts in the 
# sense of the central dogma? Are they exclusively in "mrna" (below)?
RNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [
    intact.molecule, 
    rnacentral, 
    reactome, 
    genbank, 
    ncbigene, 
    ensembl, 
    refseq
  ]
  label_in_input: [
    intact_rna, 
    rnacentral_rna, 
    reactome_rna, 
    genbank_rna,
    entrez_rna,
    ensembl_rna,
    refseq_rna
  ]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

dsRNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [intact.molecule, rnacentral, refseq]
  label_in_input: [intact_dsrna, rnacentral_dsrna, refseq_dsrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

GuideRNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [intact.molecule, rnacentral]
  label_in_input: [intact_grna, rnacentral_grna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

lncRNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [intact.molecule, refseq, rnacentral, ensembl]
  label_in_input: [intact_lncrna, refseq_lncrna, rnacentral_lncrna, ensembl_lncrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

rRNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [intact.molecule, genbank, rnacentral, ensembl, ncbigene]
  label_in_input: [intact_rrna, genbank_rrna, rnacentral_rrna, ensembl_rrna, entrez_rrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

snRNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [intact.molecule, rnacentral, ensembl, genbank]
  label_in_input: [intact_snrna, rnacentral_snrna, ensembl_snrna, genbank_snrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

snoRNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [rnacentral]
  label_in_input: [snorna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

tRNASequence:
  is_a: NucleicAcidEntity
  represented_as: node
  preferred_id: [genbank, ensembl, chebi, rnacentral]
  label_in_input: [genbank_trna, ensembl_trna, chebi_trna, rnacentral_trna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str 
    sequence: str

SmallMolecule:
  represented_as: node
  preferred_id: [chebi, chembl, intact.molecule, pubchem.compound]
  label_in_input: [chebi_small_molecule, chembl_small_molecule, intact_small_molecule, pubchem_compound]
  properties:
    ac: str
    shortName: str
    preferredName: str

StableComplex:
  is_a: MacromolecularComplexMixin
  represented_as: node
  preferred_id: complexportal
  label_in_input: complexportal_stable_complex
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str 

Stimulus:
  is_a: BiologicalEntity
  represented_as: node
  preferred_id: signor
  label_in_input: signor_stimulus
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str 


Transcript:
  represented_as: node
  preferred_id: [ensembl, intact.molecule, hgnc, genbank, refseq]
  label_in_input: [ensembl_mrna, intact_mrna, hgnc_mrna, genbank_mrna, refseq_mrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

Xenobiotic:
  is_a: SmallMolecule
  represented_as: node
  preferred_id: [pubchem.compound, chebi]
  label_in_input: [pubchem_xenobiotic, chebi_xenobiotic]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str 

# ---
# Associations
# ---
# Associations are not supposed to be represented in node form as per the 
# specifications of Biolink. However, in an analytic context, it often makes 
# sense to represent interactions as nodes in Neo4j, because it enables, for
# instance, the annotation of a relationship with a publication as source of
# evidence (also known as reification in the knowledge graph world). 

# The Biolink specifications for these types of relationships do 
# not go into depth; for example, the hierarchy for molecular interactions
# (ie, "associations") ends at "PairwiseMolecularInteraction", there are no 
# explicit terms for protein-protein-interaction, phosphorylation, miRNA-
# targeting, etc. Biolink proposes to use interaction identifiers from 
# ontologies, such as https://www.ebi.ac.uk/ols/ontologies/mi/.

PostTranslationalInteraction:
  represented_as: node
  preferred_id: intact
  source: Protein
  target: Protein
  label_in_input: [
    protein_protein_intact, 
    protein_protein_rcsb pdb, 
    protein_protein_wwpdb, 
    protein_protein_dip, 
    protein_protein_emdb, 
    protein_protein_pdbe,
    protein_protein_interpro,
    protein_protein_psi-mi,
    protein_protein_omim,
    protein_protein_tissue list,
    protein_protein_brenda,
    protein_protein_mint,
    protein_protein_proteomexchange,
    protein_protein_zfin,
    protein_protein_bmrb,
    protein_protein_wikipedia,
    protein_protein_pride,
    protein_protein_pmc,
    protein_protein_mpidb,
    protein_protein_imex,
    protein_protein_go,
    protein_protein_efo,
    protein_protein_reactome,
    protein_protein_signor
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str


### From OTAR, Barrio-Hernandez query:
# 'MI:0320', ribonucleic acid
# quite generic; probes, k-mers (shared probably), telomerase RNA
# protein_rna: intact, wwpdb, emdb, reactome
# rna_protein: intact, wwpdb, emdb, rcsb pdb
# only reactome does not have interaction ID
intact.ProteinToRNASequenceAssociation:
  is_a: [ProteinToRNASequenceAssociation, Association]
  represented_as: node
  preferred_id: intact
  source: Protein
  target: RNASequence
  label_in_input: [
    protein_rna_intact,
    protein_rna_wwpdb,
    protein_rna_emdb,
    rna_protein_intact,
    rna_protein_wwpdb,
    rna_protein_emdb,
    rna_protein_rcsb pdb,
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# hack: represent virtual leaves explicitly
reactome.ProteinToRNASequenceAssociation:
  is_a: [ProteinToRNASequenceAssociation, Association]
  represented_as: node
  preferred_id: id
  source: Protein
  target: RNASequence
  label_in_input: protein_rna_reactome
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str


# 'MI:0321', catalytic rna
# no "catalytic rna" in OTAR graph

# 'MI:0322', guide rna
# only intact and wwpdb

# 'MI:0323', heterogeneous nuclear rna
# not in OTAR graph

# 'MI_0325', transfer rna
# few; intact, emdb, wwpdb

# 'MI:0324', messenger rna
# only intact

# 'MI:0608', ribosomal rna
# few; intact, emdb, wwpdb, rcsb pdb

# 'MI:0609', small nucleolar rna
# few, only intact

# 'MI:0610', small interfering rna
# not in OTAR graph

# 'MI:0611', signal recognition particle rna
# not in OTAR graph

# 'MI:0679', poly adenine
# few, only intact

# 'MI:2190', long non-coding ribonucleic acid
# few, only intact

# 'MI:2204', micro rna few and only intact, BUT there are quite some
# more mRNA-miRNA interactions, which are disregarded in this schema;
# may be a point of improvement to include those protein-mrna-mirna
# relations
