Title: BioCypher graph schema configuration file

# This configuration file establishes the hierarchy and connectivity in a newly
# set-up BioCypher property graph database. Naming should adhere to Biolink
# nomenclature (available at https://biolink.github.io/biolink-model/ or via 
# the python module 'biolink-model-toolkit').

# The BioCypher YAML file specifies only the leaves of the hierarchy tree of
# the desired graph; the hierarchical structure of entities will be derived 
# from the Biolink model. Thus, only the immediate constituents of the graph
# need to be specified in the schema config.


# ---
# "Named Things"
# ---


microRNA:
  represented_as: node
  preferred_id: [rnacentral, ensembl, mirbase]
  label_in_input: [rnacentral_mirna, ensembl_mirna, mirbase_mirna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

peptide:
  is_a: polypeptide
  represented_as: node
  preferred_id: [intact.molecule, dip]
  label_in_input: [intact_peptide, dip_peptide]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

peptide precursor:
  is_a: [peptide, polypeptide]
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_peptide_precursor
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

poly a sequence motif:
  is_a: nucleic acid sequence motif
  represented_as: node
  preferred_id: chebi
  label_in_input: chebi_poly_a
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str

protein:
  represented_as: node
  preferred_id: [
    uniprot, 
    intact.molecule, 
    uniparc, 
    ncbigene, 
    genbank, 
    dip, 
    ipi, 
    refseq, 
    drugbank, 
    chembl, 
    ensembl
  ]
  label_in_input: [
    uniprot_protein, 
    intact_protein, 
    uniprot_archive_protein, 
    entrez_protein,
    genbank_protein,
    dip_protein,
    ipi_protein,
    refseq_protein,
    drugbank_protein,
    chembl_protein,
    ensembl_protein
  ]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

protein isoform:
  is_a: protein
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_protein_isoform
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

protein precursor:
  is_a: protein
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot_protein_precursor
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

# OTAR "rna" may be too generic; where are the actual Transcripts in the 
# sense of the central dogma? Are they exclusively in "mrna" (below)?
RNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [
    intact.molecule, 
    rnacentral, 
    reactome, 
    genbank, 
    ncbigene, 
    ensembl, 
    refseq
  ]
  label_in_input: [
    intact_rna, 
    rnacentral_rna, 
    reactome_rna, 
    genbank_rna,
    entrez_rna,
    ensembl_rna,
    refseq_rna
  ]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

guide RNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact.molecule, rnacentral]
  label_in_input: [intact_grna, rnacentral_grna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

lncRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact.molecule, refseq, rnacentral, ensembl]
  label_in_input: [intact_lncrna, refseq_lncrna, rnacentral_lncrna, ensembl_lncrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

rRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [intact.molecule, genbank, rnacentral, ensembl, ncbigene]
  label_in_input: [intact_rrna, genbank_rrna, rnacentral_rrna, ensembl_rrna, entrez_rrna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

snoRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [rnacentral]
  label_in_input: [snorna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str
    sequence: str

tRNA sequence:
  is_a: nucleic acid entity
  represented_as: node
  preferred_id: [genbank, ensembl, chebi, rnacentral]
  label_in_input: [genbank_trna, ensembl_trna, chebi_trna, rnacentral_trna]
  properties:
    ac: str
    fullName: str
    shortName: str
    preferredName: str 
    sequence: str


# ---
# Associations
# ---

# OBO MI stratification from interaction type: https://www.ebi.ac.uk/ols/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_0190&lang=en&viewMode=All&siblings=false

colocalisation:
  is_a: [post translational interaction, association]
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  # merge for now for simplicity
  label_in_input: [
    protein_protein_colocalization,
    protein_protein_proximity,

    protein_peptide_proximity,
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str
    src_role: str
    tar_role: str

functional association:
  is_a: [post translational interaction, association]
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  label_in_input: protein_protein_functional association
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str
    src_role: str
    tar_role: str

direct interaction:
  is_a: [post translational interaction, association]
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  # direct inheritance chain without branches
  label_in_input: [
    protein_protein_direct interaction,
    protein_protein_physical association,
    protein_protein_association,
    
    protein_peptide_direct interaction,
    protein_peptide_physical association,
    protein_peptide_association,

    peptide_protein_direct interaction,
    peptide_protein_physical association,
    peptide_protein_association,
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str
    src_role: str
    tar_role: str

enzymatic interaction:
  is_a: [direct interaction, post translational interaction, association]
  represented_as: node
  preferred_id: intact
  source: protein
  target: protein
  label_in_input: [
    protein_protein_acetylation,
    protein_protein_deacetylation,
    protein_protein_phosphorylation,
    protein_protein_protein cleavage,
    protein_protein_cleavage,
    protein_protein_gtpase reaction,
    protein_protein_lipid cleavage-2,
    protein_protein_lipid cleavage,
    protein_protein_enzymatic reaction,
    protein_protein_adp ribosylation,
    protein_protein_ubiquitination,
    protein_protein_redox reaction,
    protein_protein_hydroxylation,
    protein_protein_methylation,
    protein_protein_deamidation,
    protein_protein_sumoylation,
    protein_protein_neddylation,
    protein_protein_dephosphorylation,
    protein_protein_dna cleavage,
    protein_protein_glycosylation,
    protein_protein_demethylation,
    protein_protein_atpase reaction,
    protein_protein_deubiquitination,
    protein_protein_covalent binding,
    protein_protein_phosphotransfer,
    protein_protein_ampylation,
    protein_protein_deamination,
    protein_protein_disulfide bond,
    protein_protein_aminoacylation,
    protein_protein_rna cleavage,
    protein_protein_palmitoylation,
    protein_protein_lipid addition,
    protein_protein_de-adp-ribosylation reaction,
    protein_protein_rna elongation,
    protein_protein_guanine nucleotide exchange factor reaction,
    protein_protein_transglutamination,
    protein_protein_deneddylation,
    protein_protein_proline isomerization  reaction,
    protein_protein_decarboxylation,
    protein_protein_sulfurtransfer,
    protein_protein_triphosphatase react,
    protein_protein_carboxylation,
    protein_protein_isomerase reaction,
    protein_protein_phospholipase reaction,
    protein_protein_p_patetheinylation,
    protein_protein_gtpase-activating protein reaction,
    protein_protein_desumoylation,
    protein_protein_s-nitrosylation,
    protein_protein_tyrosination,
    protein_peptide_phosphorylation,
    protein_peptide_methylation,
    protein_peptide_enzymatic reaction,
    protein_peptide_demethylation,
    protein_peptide_deacetylation,
    protein_peptide_protein cleavage,
    protein_peptide_cleavage,
    protein_peptide_hydroxylation,
    protein_peptide_dephosphorylation,
    peptide_protein_phosphorylation,
    peptide_protein_cleavage,
    peptide_protein_deamination,
    peptide_protein_demethylation,
    peptide_protein_methylation,
    peptide_protein_dephosphorylation,
    peptide_protein_glycosylation,
    peptide_protein_deacetylation,
    peptide_protein_depalmitoylation,
    peptide_protein_demyristoylation,
    protein_peptide_protein cleavage,
    peptide_protein_protein cleavage,
    peptide_protein_hydroxylation,
    peptide_protein_enzymatic reaction,
    peptide_protein_acetylation
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str
    src_role: str
    tar_role: str


### From OTAR, Barrio-Hernandez query:
# 'MI:0320', ribonucleic acid
# quite generic; probes, k-mers (shared probably), telomerase RNA
# protein_rna: intact, wwpdb, emdb, reactome
# rna_protein: intact, wwpdb, emdb, rcsb pdb
# only reactome does not have interaction ID
intact.protein to RNA sequence association:
  is_a: [protein to RNA sequence association, association]
  represented_as: node
  preferred_id: intact
  source: protein
  target: RNASequence
  label_in_input: [
    protein_rna_intact,
    protein_rna_wwpdb,
    protein_rna_emdb,
    rna_protein_intact,
    rna_protein_wwpdb,
    rna_protein_emdb,
    rna_protein_rcsb pdb,
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# hack: represent virtual leaves explicitly
reactome.protein to RNA sequence association:
  is_a: [protein to RNA sequence association, association]
  represented_as: node
  preferred_id: id
  source: protein
  target: RNASequence
  label_in_input: protein_rna_reactome
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str


# 'MI:0321', catalytic rna
# no "catalytic rna" in OTAR graph

# 'MI:0322', guide rna
# only intact and wwpdb
protein to guide RNA association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: GuideRNASequence
  label_in_input: [protein_grna_intact, protein_grna_wwpdb]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# 'MI:0323', heterogeneous nuclear rna
# not in OTAR graph

# 'MI_0325', transfer rna
# few; intact, emdb, wwpdb
protein to tRNA association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: tRNASequence
  label_in_input: [
    protein_trna_intact,
    trna_protein_intact,
    protein_trna_emdb,
    protein_trna_wwpdb
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# 'MI:0324', messenger rna
# only intact
protein to mRNA association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: mRNASequence
  label_in_input: [
    protein_mrna_intact,
    mrna_protein_intact
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# 'MI:0608', ribosomal rna
# few; intact, emdb, wwpdb, rcsb pdb
protein to rRNA association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: rRNASequence
  label_in_input: [
    rrna_protein_intact,
    rrna_protein_wwpdb,
    rrna_protein_rcsb pdb,
    protein_rrna_intact,
    rrna_protein_emdb,
    protein_rrna_emdb,
    protein_rrna_wwpdb
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# 'MI:0609', small nucleolar rna
# few, only intact
protein to snoRNA association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: snoRNASequence
  label_in_input: protein_snorna_intact
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# 'MI:0610', small interfering rna
# not in OTAR graph

# 'MI:0611', signal recognition particle rna
# not in OTAR graph

# 'MI:0679', poly adenine
# few, only intact
protein to poly a sequence motif association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: PolyASequenceMotif
  label_in_input: [
    poly a_protein_intact,
    protein_poly a_intact
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# 'MI:2190', long non-coding ribonucleic acid
# few, only intact
protein to lncRNA sequence association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: lncRNASequence
  label_in_input: [
    protein_lncrna_intact,
    lncrna_protein_intact
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str

# 'MI:2204', micro rna few and only intact, BUT there are quite some
# more mRNA-miRNA interactions, which are disregarded in this schema;
# may be a point of improvement to include those protein-mrna-mirna
# relations
protein to microRNA sequence association:
  is_a: association
  represented_as: node
  preferred_id: intact
  source: protein
  target: microRNA
  label_in_input: [
    mirna_protein_intact,
    protein_mirna_intact
  ]
  properties:
    ac: str
    shortName: str
    isNegative: str
    isInferred: str
    interactionTypeShortName: str
    interactionTypeFullName: str
    interactionTypeIdentifierStr: str
