gene:
  represented_as: node
  preferred_id: ensembl
  label_in_input: gene

disease:
  represented_as: node
  preferred_id: [mondo, efo, hp]
  label_in_input: [mondo, efo, hp]

gene to disease association:
  represented_as: edge
  preferred_id: [affected pathway, orphanet, somatic mutation, genetic association]
  label_in_input: [affected_pathway, orphanet, somatic_mutation, genetic_association]